name: Build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Build Environment
        # Create a separate build directory
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Setup Environment
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends \
            ninja-build clang cmake gcc-multilib \
            libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev \
            libxinerama-dev libxi-dev libxext-dev libxfixes-dev \
            libwayland-dev libwayland-bin libxkbcommon-dev

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build Project
        working-directory: ${{github.workspace}}/build
        run: cmake --build .
